//go:build ignore

// Regenerate with: go run tests/e2e/generate-fixtures.go
package main

import (
	"encoding/json"
	"github.com/jxburros/GWatch/internal/checks"
	"os"
)

func main() {
	b, err := json.MarshalIndent(checks.Templates(), "", "  ")
	if err != nil {
		panic(err)
	}
	b = append([]byte("// Generated by go run tests/e2e/generate-fixtures.go; do not edit.\nexport default "), b...)
	b = append(b, []byte(";\n")...)
	if err := os.WriteFile("web/mock-templates.js", b, 0644); err != nil {
		panic(err)
	}
}
