import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { test, expect } from '@playwright/test';
test('real service: accounts, sign-in, keys and masked check credentials', async ({ page, request }) => {
  test.setTimeout(180000);
  await page.addInitScript(() => { localStorage.setItem('gw.onboarding.done', '1'); localStorage.setItem('gw.tips.enabled', '0'); });
  const settings = await (await request.get('/api/settings')).json();
  settings.updates = { ...settings.updates, checkAutomatically: false, promptOnOpen: false };
  expect((await request.put('/api/settings', { data: settings })).ok()).toBeTruthy();
  const account = { username: 'browser-admin', password: 'browser-test-password-2026', role: 'admin' };
  expect((await request.post('/api/users', { data: account })).ok()).toBeTruthy();
  await page.goto('/#/login');
  await page.getByLabel('User name', { exact: true }).fill(account.username);
  await page.getByLabel('Password', { exact: true }).fill(account.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.locator('#page-title')).not.toHaveText('Sign in');
  await page.goto('/#/settings/users');
  await expect(page.getByText(account.username, { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'New API key' }).click();
  await page.getByRole('dialog').getByLabel('Name', { exact: true }).fill('Browser regression');
  await page.getByRole('button', { name: 'Create key', exact: true }).click();
  await expect(page.locator('.key-reveal')).toContainText('gw_');
  await page.keyboard.press('Escape');
  const response = await request.post('/api/nodes', { data: { name: 'Credential regression', host: '127.0.0.1', enabled: false, checks: [{ type: 'snmp', name: 'SNMP', enabled: false, intervalSeconds: 60, timeoutSeconds: 5, retries: 0, config: { snmpVersion: '2c', snmpCommunity: 'browser-secret', snmpOids: [{ oid: '1.3.6.1.2.1.1.3.0', name: 'Uptime', kind: 'gauge', scale: 1 }] } }] } });
  expect(response.ok()).toBeTruthy();
  const node = await response.json();
  await page.goto(`/#/nodes/${node.id}/edit`);
  await expect(page.getByLabel('Community string', { exact: true })).toHaveValue('');
  await expect(page.getByText(/A value is stored/).first()).toBeVisible();
  await expect(page.locator('body')).not.toContainText('browser-secret');
  const keyResponse = await request.post('/api/apikeys', { data: { name: 'MCP browser integration', scope: 'readwrite' } });
  expect(keyResponse.ok()).toBeTruthy();
  const { key } = await keyResponse.json();
  const { key: readKey } = await (await request.post('/api/apikeys', { data: { name: 'MCP read integration', scope: 'read' } })).json();
  await promisify(execFile)('go', ['test', './internal/e2e', '-count=1'], { cwd: 'mcp', env: { ...process.env, GWATCH_E2E_URL: new URL(page.url()).origin, GWATCH_E2E_KEY: key, GWATCH_E2E_WRITE: '1', GWATCH_E2E_READ_KEY: readKey, GWATCH_E2E_WRITE_KEY: key }, timeout: 120000 });
  const templates = await (await request.get('/api/templates')).json();
  expect(templates.map((t) => t.id)).toContain('this-computer');
  await page.goto('/?mock=1#/nodes');
  await expect(page.locator('#gwatch-mock-banner')).toHaveCount(0);
  await expect(page.getByText('Credential regression', { exact: true }).first()).toBeVisible();
});
