package store

import (
	"context"
	"errors"
	"strings"

	"github.com/jackc/pgx/v5/pgconn"
)

// postgresDialect talks to PostgreSQL through jackc/pgx's database/sql
// adapter. The differences from SQLite that matter here: $1-style
// placeholders, RETURNING instead of LastInsertId, identity columns instead
// of AUTOINCREMENT, no COLLATE NOCASE (a unique index on LOWER(username)
// stands in for it), and a 32-bit INTEGER, which is why every integer column
// becomes BIGINT.
type postgresDialect struct{}

func (postgresDialect) name() string  { return "postgres" }
func (postgresDialect) label() string { return "PostgreSQL (jackc/pgx)" }

func (postgresDialect) rebind(q string) string { return numberPlaceholders(q) }

func (d postgresDialect) schema(stmts []string) []string {
	var out []string
	for _, stmt := range stmts {
		t, ok := parseCreateTable(stmt)
		if !ok {
			out = append(out, stmt)
			continue
		}
		var extra []string
		for i, def := range t.defs {
			if isConstraint(def) {
				continue
			}
			name, typ, rest := splitColumn(def)
			upperRest := strings.ToUpper(rest)
			if strings.Contains(upperRest, "COLLATE NOCASE") {
				// users.username: case-insensitive uniqueness through an
				// index on the lower-cased value, checked by ciEq.
				rest = strings.TrimSpace(strings.Replace(strings.Replace(rest, "UNIQUE COLLATE NOCASE", "", 1), "COLLATE NOCASE", "", 1))
				extra = append(extra, "CREATE UNIQUE INDEX IF NOT EXISTS idx_"+t.name+"_"+name+"_ci ON "+t.name+" (LOWER("+name+"))")
			}
			t.defs[i] = strings.TrimSpace(name + " " + d.columnType(typ, rest))
		}
		out = append(out, t.String(""))
		out = append(out, extra...)
	}
	return out
}

// columnType maps a SQLite column type (and the clauses after it) to the
// PostgreSQL form.
func (postgresDialect) columnType(typ, rest string) string {
	upperRest := strings.ToUpper(rest)
	switch typ {
	case "INTEGER":
		if strings.HasPrefix(upperRest, "PRIMARY KEY AUTOINCREMENT") {
			return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" + rest[len("PRIMARY KEY AUTOINCREMENT"):]
		}
		return "BIGINT " + rest
	case "REAL":
		return "DOUBLE PRECISION " + rest
	}
	return typ + " " + rest
}

func (d postgresDialect) ddl(stmt string) string {
	// ALTER TABLE t ADD COLUMN name TYPE rest…
	fields := strings.Fields(stmt)
	for i, f := range fields {
		if strings.EqualFold(f, "COLUMN") && i+2 < len(fields) {
			head := strings.Join(fields[:i+2], " ")
			typ := strings.ToUpper(fields[i+2])
			rest := strings.Join(fields[i+3:], " ")
			return strings.TrimSpace(head + " " + d.columnType(typ, rest))
		}
	}
	return stmt
}

func (postgresDialect) upsertClause(keys, cols []string) string { return excludedUpsert(keys, cols) }

func (postgresDialect) insertIgnore(table string, cols []string) string {
	return insertValues(table, cols) + " ON CONFLICT DO NOTHING"
}

func (postgresDialect) insertID(ctx context.Context, ex execer, q string, args ...any) (int64, error) {
	var id int64
	err := ex.QueryRowContext(ctx, q+" RETURNING id", args...).Scan(&id)
	return id, err
}

func (postgresDialect) ci(col string) string   { return "LOWER(" + col + ")" }
func (postgresDialect) ciEq(col string) string { return "LOWER(" + col + ") = LOWER(?)" }

func (postgresDialect) intDiv(a, b string) string    { return "(" + a + "/" + b + ")" }
func (postgresDialect) castInt(expr string) string   { return "CAST(" + expr + " AS BIGINT)" }
func (postgresDialect) jsonArray(expr string) string { return "json_build_array(" + expr + ")::text" }

func (postgresDialect) hasTable(ctx context.Context, s *Store, table string) (bool, error) {
	var n int
	err := s.queryRow(ctx, "SELECT count(*) FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?", table).Scan(&n)
	return n > 0, err
}

func (postgresDialect) tableColumns(ctx context.Context, s *Store, table string) (map[string]bool, error) {
	return informationSchemaColumns(ctx, s, "current_schema()", table)
}

// syncSequence moves the identity sequence past the largest id in table.
// GENERATED BY DEFAULT lets a restore insert rows with the ids they had, but
// the sequence does not notice, and the next generated id would collide with
// one of them.
func (postgresDialect) syncSequence(ctx context.Context, tx *wtx, table string) error {
	_, err := tx.exec(ctx, "SELECT setval(pg_get_serial_sequence('"+table+"', 'id'), COALESCE((SELECT MAX(id) FROM "+table+"), 0) + 1, false)")
	return err
}

func pgCode(err error) string {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return pgErr.Code
	}
	return ""
}

func (postgresDialect) isUniqueViolation(err error) bool { return pgCode(err) == "23505" }
func (postgresDialect) isDuplicateColumn(err error) bool { return pgCode(err) == "42701" }
func (postgresDialect) isDuplicateIndex(err error) bool  { return pgCode(err) == "42P07" }

// A server has its own checkpointing and vacuuming, on its own schedule.
func (postgresDialect) checkpoint(ctx context.Context, s *Store) error { return nil }
func (postgresDialect) vacuum(ctx context.Context, s *Store) error     { return nil }

// sizeBytes adds up the tables in the schema GWatch uses, indexes included.
func (postgresDialect) sizeBytes(ctx context.Context, s *Store) int64 {
	var n int64
	_ = s.queryRow(ctx, `SELECT COALESCE(SUM(pg_total_relation_size(c.oid)), 0)::BIGINT
		FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = current_schema() AND c.relkind = 'r'`).Scan(&n)
	return n
}

// serializeWrites is true here as well, although a server would take
// concurrent writers happily: the store's transactions were written for a
// single writer and have never had to think about two of them interleaving,
// and correctness comes before throughput. Lifting this is a possible later
// optimisation, not a promise.
func (postgresDialect) serializeWrites() bool { return true }
func (postgresDialect) fileBacked() bool      { return false }

// informationSchemaColumns is the column probe PostgreSQL and MySQL share,
// differing only in how the current schema is spelled.
func informationSchemaColumns(ctx context.Context, s *Store, schemaExpr, table string) (map[string]bool, error) {
	rows, err := s.query(ctx, "SELECT column_name FROM information_schema.columns WHERE table_schema = "+schemaExpr+" AND table_name = ?", table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	have := map[string]bool{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		have[name] = true
	}
	return have, rows.Err()
}
